// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njuzewrtskqhwggkaslt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qdXpld3J0c2txaHdnZ2thc2x0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMDkxNDMsImV4cCI6MjA1NjU4NTE0M30.E1I2IpXMx-FzIRGp9foGluLrsr0JhLk6st91Zlw8QNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);